apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: get-products
    visualize: "true"
  name: get-products-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: get-products
        visualize: "true"
    spec:
      containers:
        - image: get-products:{{CONTAINER_VERSION}}
          name: get-products
          ports:
            - name: hazlecast
              containerPort: 5701
              #hostPort: 5701