apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: login
    visualize: "true"
  name: login-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: login
        visualize: "true"
    spec:
      containers:
        - image: login:{{CONTAINER_VERSION}}
          name: login
          ports:
            - name: hazelcast
              containerPort: 5701
              #hostPort: 5701