apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: pay-build
    visualize: "true"
  name: pay-build-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: pay-build
        visualize: "true"
    spec:
      containers:
        - image: pay-build:{{CONTAINER_VERSION}}
          name: pay-build
          ports:
            - name: hazlecast
              containerPort: 5701
              #hostPort: 5701