apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: reporting
    visualize: "true"
  name: reporting-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: reporting
        visualize: "true"
    spec:
      containers:
        - image: reporting:{{CONTAINER_VERSION}}
          name: reporting
          ports:
            - name: hazelcast
              containerPort: 5701