apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
    visualize: "true"
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        visualize: "true"
    spec:
      containers:
        - image: api-gateway:{{CONTAINER_VERSION}}
          name: api-gateway
          ports:
            - name: api-gateway
              containerPort: 8080
              hostPort: 8080
            - name: hazlecast
              containerPort: 5701
              #hostPort: 5701