apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-tables
    visualize: "true"
  name: get-tables-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-tables
  template:
    metadata:
      labels:
        app: get-tables
        visualize: "true"
    spec:
      containers:
        - image: get-tables:{{CONTAINER_VERSION}}
          name: get-tables
          ports:
            - name: hazelcast #Limit 15 characters
              containerPort: 5701
              #hostPort: 5701