apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-menus
    visualize: "true"
  name: get-menus-deployment
spec:
  selector:
    matchLabels:
      app: get-menus
  replicas: 1
  template:
    metadata:
      labels:
        app: get-menus
        visualize: "true"
    spec:
      containers:
        - image: get-menus:{{CONTAINER_VERSION}}
          name: get-menus
          ports:
            - name: hazelcast #Limit 15 characters
              containerPort: 5701