apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hazelcast-management-center
    visualize: "true"
  name: hazelcast-management-center
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hazelcast-management-center
  template:
    metadata:
      labels:
        app: hazelcast-management-center
        visualize: "true"
    spec:
      containers:
        - image: hazelcast/management-center:3.9 #:3.9 ou :3.6
          name: container-hazelcast-management-center
          ports:
            - name: mancenter
              containerPort: 8080
              hostPort: 8080
            - name: hazelcast
              containerPort: 5701
              #hostPort: 5701