apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
    visualize: "true"
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        visualize: "true"
    spec:
      containers:
        - image: mongo:3.6
          name: mongo
          ports:
            - name: mongo
              containerPort: 27017
              hostPort: 27017