apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pay-build
    visualize: "true"
  name: pay-build-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay-build
  template:
    metadata:
      labels:
        app: pay-build
        visualize: "true"
    spec:
      containers:
        - image: pay-build:{{CONTAINER_VERSION}}
          name: pay-build
          ports:
            - name: hazelcast
              containerPort: 5701
              #hostPort: 5701