apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registar-user
    visualize: "true"
  name: registar-user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registar-user
  template:
    metadata:
      labels:
        app: registar-user
        visualize: "true"
    spec:
      containers:
        - image: registar-user:{{CONTAINER_VERSION}}
          name: registar-user
          ports:
            - name: hazelcast
              containerPort: 5701