apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reporting
    visualize: "true"
  name: reporting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting
  template:
    metadata:
      labels:
        app: reporting
        visualize: "true"
    spec:
      containers:
        - image: reporting:{{CONTAINER_VERSION}}
          name: reporting
          ports:
            - name: hazelcast
              containerPort: 5701
              #hostPort: 5701