apiVersion: v1
kind: Service
metadata:
  labels:
    name: get-products
    visualize: "true"
    service-name: cluster01
  name: get-products
spec:
  ports:
    - port: 5701
      targetPort: 5701
      name: hazelcast
  selector:
    name: get-products
