apiVersion: v1
kind: Service
metadata:
  labels:
    name: login
    visualize: "true"
    cluster01: "true"
    service-name: cluster01
  name: login
spec:
  ports:
    - port: 5701
      targetPort: 5701
      name: hazelcast
  selector:
    name: login
