apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
    visualize: "true"
    cluster01: "true"
    service-name: cluster01
  name: mongo
spec:
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
  selector:
    name: mongo